{
 "title": "net-status",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "LB1 VIP become_master",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "keepalived_vrrp_become_master{instance=\"lb1:9165\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LB2 VIP become_master",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "keepalived_vrrp_become_master{instance=\"lb2:9165\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "LB 1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": " rate(nginx_vts_server_requests_total{host=\"*\", instance=\"lb1:80\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LB 2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": " rate(nginx_vts_server_requests_total{host=\"*\", instance=\"lb2:80\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}